' <auto-generated/>
' Copyright (c) Traeger Industry Components GmbH. All Rights Reserved. https://www.traeger.de/
Imports Opc.UaFx
Imports System
Imports System.CodeDom.Compiler

Namespace Global.Opc.UaFx.ServerDataTypes.Machines

    <OpcDataTypeAttribute("ns=2;s=MachineJob")>
    <OpcDataTypeEncodingAttribute("ns=2;s=MachineJob.Binary", Type:=Opc.UaFx.OpcEncodingType.Binary, NamespaceUri:="http://sampleserver/machines")>
    <OpcDataTypeEncodingMask(OpcEncodingMaskKind.Auto)>
    <CLSCompliantAttribute(False)>
    Public Class MachineJob
        Public Property Number As String

        <OpcDataTypeMemberSwitchAttribute>
        Public Property Duration As Integer?

        Public Property EstimatedDuration As Integer

        Public Property InProcess As Boolean

        <OpcDataTypeMemberLengthAttribute(4UI)>
        Public Property CuttingPositions As Integer()

        Public Property RequiredSetup As Integer

        Public Property ScheduleTime As Date
    End Class

    <OpcDataTypeAttribute("ns=2;s=ManufacturingOrder")>
    <OpcDataTypeEncodingAttribute("ns=2;s=ManufacturingOrder.Binary", Type:=Opc.UaFx.OpcEncodingType.Binary, NamespaceUri:="http://sampleserver/machines")>
    <CLSCompliantAttribute(False)>
    <GeneratedCodeAttribute("OPC Watch by Traeger.de", "2.10.0.0")>
    Public Class ManufacturingOrder
        Public Property Article As String

        Public Property Order As String

        Public Property JobsLength As Integer

        <OpcDataTypeMemberLengthAttribute(NameOf(JobsLength))>
        Public Property Jobs As Opc.UaFx.ServerDataTypes.Machines.MachineJob()
    End Class

    <OpcDataTypeAttribute("ns=2;s=MachineStatus")>
    <CLSCompliantAttribute(False)>
    <GeneratedCodeAttribute("OPC Watch by Traeger.de", "2.10.0.0")>
    Public Enum MachineStatus
        Unknown = 0
        Stopped = 1
        Started = 2
        WaitingForOrders = 3
        Suspended = 4
    End Enum

    <OpcDataTypeAttribute("ns=2;s=MachineSetup")>
    <CLSCompliantAttribute(False)>
    <GeneratedCodeAttribute("OPC Watch by Traeger.de", "2.10.0.0")>
    Public Enum MachineSetup
        Manual = 0
        Corrugator = 1
        Cutter = 2
        Printer1 = 4
        Printer2 = 8
        Laminator = 16
        Packager = 3
        DisplayLine = 27
        Finisher = 20
    End Enum

End Namespace
