// <auto-generated/>
// Copyright (c) Traeger Industry Components GmbH. All Rights Reserved. https://www.traeger.de/
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace Opc.UaFx.ServerDataTypes.Machines
{
    using Opc.UaFx;
    using System;
    using System.CodeDom.Compiler;

    [OpcDataTypeAttribute("ns=2;s=MachineJob")]
    [OpcDataTypeEncodingAttribute("ns=2;s=MachineJob.Binary", Type = Opc.UaFx.OpcEncodingType.Binary, NamespaceUri = "http://sampleserver/machines")]
    [OpcDataTypeEncodingMask(OpcEncodingMaskKind.Auto)]
    [CLSCompliantAttribute(false)]
    public class MachineJob
    {
        public string Number
        {
            get;
            set;
        }

        [OpcDataTypeMemberSwitchAttribute]
        public int? Duration
        {
            get;
            set;
        }

        public int EstimatedDuration
        {
            get;
            set;
        }

        public bool InProcess
        {
            get;
            set;
        }

        [OpcDataTypeMemberLengthAttribute(4U)]
        public int[] CuttingPositions
        {
            get;
            set;
        }

        public int RequiredSetup
        {
            get;
            set;
        }

        public System.DateTime ScheduleTime
        {
            get;
            set;
        }
    }

    [OpcDataTypeAttribute("ns=2;s=ManufacturingOrder")]
    [OpcDataTypeEncodingAttribute("ns=2;s=ManufacturingOrder.Binary", Type = Opc.UaFx.OpcEncodingType.Binary, NamespaceUri = "http://sampleserver/machines")]
    [CLSCompliantAttribute(false)]
    [GeneratedCodeAttribute("OPC Watch by Traeger.de", "2.10.0.0")]
    public class ManufacturingOrder
    {
        public string Article
        {
            get;
            set;
        }

        public string Order
        {
            get;
            set;
        }

        public int JobsLength
        {
            get;
            set;
        }

        [OpcDataTypeMemberLengthAttribute(nameof(JobsLength))]
        public Opc.UaFx.ServerDataTypes.Machines.MachineJob[] Jobs
        {
            get;
            set;
        }
    }

    [OpcDataTypeAttribute("ns=2;s=MachineStatus")]
    [CLSCompliantAttribute(false)]
    [GeneratedCodeAttribute("OPC Watch by Traeger.de", "2.10.0.0")]
    public enum MachineStatus
    {
        Unknown = 0,
        Stopped = 1,
        Started = 2,
        WaitingForOrders = 3,
        Suspended = 4
    }

    [OpcDataTypeAttribute("ns=2;s=MachineSetup")]
    [CLSCompliantAttribute(false)]
    [GeneratedCodeAttribute("OPC Watch by Traeger.de", "2.10.0.0")]
    public enum MachineSetup
    {
        Manual = 0,
        Corrugator = 1,
        Cutter = 2,
        Printer1 = 4,
        Printer2 = 8,
        Laminator = 16,
        Packager = 3,
        DisplayLine = 27,
        Finisher = 20
    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
